# Generated by Django 3.0.7 on 2020-07-15 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200715_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 7, 15, 5, 50, 58, 867312, tzinfo=utc), upload_to='media/post/'),
            preserve_default=False,
        ),
    ]
